### ISSUE TITLE
When a new release?

### ISSUE THREAD

**Issue by duvh93** [SolidHal/PrawnOS#222]
Hello!

Are there going to be new releases in the foreseeable future? Shall I build PrawnOS from sources myself?

**Comment by Maccraft123** [comment]
Yes

**Comment by SolidHal** [comment]
There will be a release `Soon`. In the meantime, you can grab a daily from the github CI for any commit if you'd like. 
The main item holding back a release is packaging. PrawnOS specific modifications are currently difficult to upgrade without a full reinstall. I would like to get all of the filesystem items packaged and uploaded to the repo so that a user can upgrade portions of the system as need be. 
I would also like to get panfrost/mesa >=20.2 working, so I am currently focusing on (re)packaging panfrost/mesa for debian 10.

**Comment by SolidHal** [comment]
Now!
