### ISSUE TITLE
cannot install keepassxc

### ISSUE THREAD

**Issue by Anthony-Sensors** [SolidHal/PrawnOS#71]
sudo apt install keepassxc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 keepassxc : Depends: libgcrypt20 (>= 1.8.0) but 1.7.6-2+deb9u3 is to be installed
             Depends: libqt5core5a (>= 5.10.0) but 5.7.1+dfsg-3+b1 is to be installed
             Depends: libqt5widgets5 (>= 5.11.0~rc1) but 5.7.1+dfsg-3+b1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by SolidHal** [comment]
This is for two reasons.
First, keepassxc isnt available in stretch. https://packages.debian.org/search?searchon=names&keywords=keepassxc Only in backports. 

So it tries to pull it from testing, but without the -t testing, it isn't allowed to pull dependencies from testing. 

Ive added stretch backports as I don't see any reason to not include it. I've also fixed up the apt pinning so that backports is used after stable. 

This was done in commit cf4d9f8327cd7f35d8eda6b58446fbad30b68ef8
I'll be making a new release once this is fully tested. 

If you don't want to download a new release to fix this, you can just copy the changes into /etc/apt/preferences and /etc/apt/sources.list.
