### ISSUE TITLE
Sound does not work on certain video in firefox

### ISSUE THREAD

**Issue by Anthony-Sensors** [SolidHal/PrawnOS#79]
Certain streaming video does not output sound other do output sound.

**Comment by SolidHal** [comment]
I've noticed this as well. Looking at youtube videos "stats for nerds", it seems to depend on how the audio volume is normalized. Using a plugin in firefox like this one lets you adjust how firefox handles sound and seems to let me workaround this issue https://addons.mozilla.org/en-US/firefox/addon/soundfixer/

Because of this, it leads me to believe the cause is firefox itself and not the system. A bug should probably be opened for debians armhf firefox package.

**Comment by Anthony-Sensors** [comment]
Yes workaround wokrs for me too.
